/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package markovstringgenerator;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.io.File;
import java.io.FileNotFoundException;
import javafx.stage.Stage;

public class App {
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws FileNotFoundException {
        
        Trie trie = new Trie();
        File nimilista = new File("/home/alkaakin/markov_string_generator/markovstringgenerator/nimilista.txt");
        FileInputStream stream = new FileInputStream(nimilista);
        BufferedReader reader = new BufferedReader(new InputStreamReader(stream));
        trie.fileToTrie(nimilista);
        //trie.fileToTrie(nimilista);
        trie.printWords('k');

        System.out.println(trie.markovAutoComplete("Vain"));
        
    }
}
