/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package markovstringgenerator;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.io.File;
import java.io.FileNotFoundException;
import javafx.stage.Stage;

public class App {
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws FileNotFoundException {
        
        Trie trie = new Trie();
        System.out.print(trie.searchTrie("ADD"));
        trie.insertTrie("ADD");
        System.out.print(trie.searchTrie("ADD"));
        File nimilista = new File("/home/alkaakin/markov_string_generator/markovstringgenerator/nimilista.txt");
        FileInputStream stream = new FileInputStream(nimilista);
        BufferedReader reader = new BufferedReader(new InputStreamReader(stream));
        trie.fileToTrie(nimilista);
        System.out.print(trie.searchTrie("Arwen"));
        System.out.print(trie.searchTrie("Alastair"));
        System.out.print(trie.searchTrie("Orpana"));
        System.out.print(trie.searchTrie("Arwena"));
        System.out.print(trie.searchTrie("Arwe"));
        System.out.print(trie.searchTrie("Aleksi"));
        System.out.print(trie.searchTrie("Aleks"));
        System.out.print(trie.searchTrie("Aleksii"));
        trie.insertTrie("Aleksii");
        System.out.println(trie.searchTrie("Aleksii"));
        System.out.println("\n");
        System.out.println("testi");
        System.out.println("\n");
        System.out.println(trie.searchTrie("Inka"));
        trie.insertTrie("Inka");
        System.out.println("\n");
        System.out.println(trie.searchTrie("Inka"));
        System.out.println(trie.root.getCharacters());
        System.out.println(trie.root.getChild("a"));
        System.out.println(trie.root.getAllChildren("a"));
        //testVisualization testi = new testVisualization();
        //Stage stage = new Stage();
        //testi.start(stage);
    }
}
